### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by silenius** [Pylons/trypyramid.com#231] opened 2017-05-04 09:15 UTC
The search seems broken on `docs.pylonsproject.org` for the `Pyramid` project.

Steps to reproduce:
 1. Go to https://trypyramid.com/resources.html
 2. Under Documentation click `HTML` for `1.8` (http://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/)
 3. In the `Quick search` box search for something, let's say `remember` (http://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/search.html?q=remember&check_keywords=yes&area=default)
 4. Search works, but links are somewhat broken (gives a "SORRY This page does not exist yet.")

**Comment by stevepiercy** [comment] 2017-05-04 09:59
Thanks for the report. This is a known issue with Read the Docs and its search feature. We're tracking it in the Pyramid repo. Closing as duplicate of https://github.com/Pylons/pyramid/issues/3026.

**Closed by stevepiercy** 2017-05-04 09:59 UTC
